## These two function allow to cache the result of a matrix inversion.
## 

## This function creates a vector with instruction on how to get and solve a matrix 

makeCacheMatrix <- function(x = matrix()) {
  inv= NULL
  set <- function(y) {
    x <<- y
    inv <<- NULL
  }
  get <- function() x
  setinv = function(solve) inv <<- solve
  getinv = function() inv
  list(set = set, get = get,
       setinv = setinv,
       getinv = getinv)
}


## This solves the matrix from the object generated by the previous function, and chaces it so it does not need to be recalculated. 

cacheSolve <- function(x, ...) {
  m <- x$getinv()
  if(!is.null(m)) {
    message("getting cached data")
    return(m)
  }
  data <- x$get()
  m <- solve(data, ...)
  x$setinv(m)
  m
}
